//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKD_ClothesShop.Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGhiNo
    {
        public string SoPhieuGhiNo { get; set; }
        public System.DateTime NgayTra { get; set; }
        public decimal SoTienTra { get; set; }
        public string SoHoaDon { get; set; }
        public string GhiChu { get; set; }
        public bool Status { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
